[package]
name = "multi-grpc-consumer-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.196", features = ["derive"] }
tonic = "0.12.3"
prost = "0.13"

[dev-dependencies]
pact_consumer = "1.4.1"
serde_json = "1.0.120"